# Generated by Django 3.2.2 on 2021-05-14 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystore', '0010_billingadress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAdress',
            new_name='BillingAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.billingaddress'),
        ),
    ]
