# Generated by Django 3.2.2 on 2021-05-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_auto_20210514_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='country',
            new_name='countries',
        ),
    ]
