# Generated by Django 3.2.2 on 2021-05-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_auto_20210515_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='visa_charge_id',
            new_name='stripe_charge_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='visa_customer_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
