# Generated by Django 3.2.2 on 2021-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_auto_20210515_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
