# Generated by Django 3.2.2 on 2021-05-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0016_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'Laptops'), ('C', 'Computers'), ('M', 'Mobiles')], max_length=2),
        ),
    ]
