# Generated by Django 3.2.2 on 2021-05-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
