# Generated by Django 3.2.2 on 2021-05-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0019_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_text',
            field=models.CharField(default='New', max_length=10),
            preserve_default=False,
        ),
    ]
