# Generated by Django 3.2.2 on 2021-05-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0020_item_label_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_text',
            field=models.CharField(max_length=50),
        ),
    ]
