# Generated by Django 3.2.2 on 2021-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0024_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
