# Generated by Django 3.2.2 on 2021-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0025_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
