# Generated by Django 3.2.2 on 2021-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0030_auto_20210518_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
