# Generated by Django 3.2.2 on 2021-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0031_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
